title: Archétype QC
description: Description à définir!
theme: just-the-docs

url: https://archetype-qc.github.io

aux_links:
  Link to Github repository: https://github.com/Archetype-QC

# Set a path/url to a logo that will be displayed instead of the title
logo: "/assets/images/logo-test.png"

# Enable or disable the site search
# Supports true (default) or false
search_enabled: true